[package]
name = "reflink-sync"
version = "0.1.0"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]
edition = "2021"

[dependencies]
clap = { version = "=3.2.17", features = ["derive", "unstable-v4"] }
reflink = "=0.1.3"
same-file = "1.0.6"
walkdir = "2.3.2"
