[package]
name = "reflink-sync"
version = "0.1.0"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]
edition = "2018"

[dependencies]
reflink = "=0.1.3"
same-file = "1"
structopt = "0.2.18"
walkdir = "2"
