name: Format Workflow
on:
  push:
    paths: ["**.md", "**.toml", "**.js", "**.json", "**.ts"]
  pull_request:
    paths: ["**.md", "**.toml", "**.js", "**.json", "**.ts"]

jobs:
  dprint:
    name: Dprint [Formatter]
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Docs | Format
        uses: dprint/check@v2.3
