# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

---
name: Main workflow
on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Install stable toolchain
        run:  rustup toolchain install stable --profile minimal --no-self-update

      - name: Run cargo check
        run: cargo check

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Install nightly toolchain
        run: rustup toolchain install nightly --profile minimal --component rustfmt,clippy --no-self-update

      - parallel:
        - name: Run cargo fmt
          run: cargo fmt --all -- --check
  
        - name: Run cargo clippy
          run: cargo clippy -- -D warnings
